dataset_archive_root = "/content/drive/MyDrive/datasets/books.zip"
dataset_root = "/content/train"
tokens_bin_file = "/content/train/tokens.bin"
vocab_bin_file ="/content/train/vocab.txt"
save_path = "/content/drive/MyDrive/dl_models/books"